name: Tessera Release Build

on:
  repository_dispatch:
    types: [release]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create release branch
        run: |
          git config user.name "melowe"
          export now=`date +%Y%m%d%H%M%S`
          git checkout -b "release-$now"

      - name: Release Prepare
        run: |
          mvn --settings .maven.xml release:prepare -DskipTests -Darguments="-DskipTests"
      - name: Release Perform
        run: |
          echo "${GPG_SECRET_KEYS}" | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
          mvn --settings .maven.xml release:perform -DskipTests -Darguments="-DskipTests"
